version: "3.0"
services:
  web:
    image: nginx:latest
    build: .
    restart: unless-stopped
    ports: 
      - "8082:80"
    volumes:
       - vol_wp:/var/www/html
  wordpress: 
    image: wordpress:5.8.0-php7.4-fpm
    expose:
      - "9000"
    restart: unless-stopped
    volumes:
      - vol_wp:/var/www/html
    environment: 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: yusepe
      WORDPRESS_DB_PASSWORD: ${USER_PASSWORD}
  db:
    image: mariadb:10.6.3-focal
    restart: unless-stopped
    volumes:
      - vol_db:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: yusepe
      MYSQL_PASSWORD:  ${USER_PASSWORD}
  phpmyadmin:
    image: phpmyadmin:5.1.1-apache
    restart: unless-stopped
    ports:
        - 8000:80
    environment:
      PMA_HOST: db
volumes: 
  vol_db:
  vol_wp:
  vol_nginx:





